### ISSUE TITLE
Probleem bij laden van een levering

### ISSUE THREAD

**Issue by Avdmaat** [diethard2/b4udignl#12]
De volgende levering geeft een foutmelding:

[Levering_20G131238_1.zip](https://github.com/diethard2/b4udignl/files/4279967/Levering_20G131238_1.zip)

TypeError: 'NoneType' object is not iterable 
Traceback (most recent call last):
  File "C:/Users/avmt/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\b4udignl2\B4UdigNLDialog.py", line 399, in on_openMsgButton_clicked
    self._loadMsg()
  File "C:/Users/avmt/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\b4udignl2\B4UdigNLDialog.py", line 561, in _loadMsg
    doc = self._openMsg(str(self.__dir))
  File "C:/Users/avmt/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\b4udignl2\B4UdigNLDialog.py", line 597, in _openMsg
    doc = wv.Doc(p_path)
  File "C:/Users/avmt/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\b4udignl2\core\wv.py", line 73, in __init__
    self._set_attributes_from_imkl()
  File "C:/Users/avmt/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\b4udignl2\core\wv.py", line 265, in _set_attributes_from_imkl
    self.storage.fill()
  File "C:/Users/avmt/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\b4udignl2\core\wv_storage.py", line 168, in fill
    self._fill_netowners()
  File "C:/Users/avmt/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\b4udignl2\core\wv_storage.py", line 396, in _fill_netowners
    self._process_bijlagen_netbeheerders()
  File "C:/Users/avmt/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\b4udignl2\core\wv_storage.py", line 488, in _process_bijlagen_netbeheerders
    self._process_bijlagen_beheerdersinfo(netowner, beheerdersinfo)
  File "C:/Users/avmt/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\b4udignl2\core\wv_storage.py", line 513, in _process_bijlagen_beheerdersinfo
    for bijlage in themabijlagen:
TypeError: 'NoneType' object is not iterable

Python versie: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS versie: 3.10.3-A Coruña A Coruña, 0e1f846438

**Comment by diethard2** [comment]
Gereproduceerd en ik ga dit zo spoedig mogelijk oplossen.
Ik verwacht aan het einde van de middag een nieuwe versie te kunnen aanbieden bij de centrale repository, waarin dit probleem is opgelost. 
Maar het kan even duren voordat deze wordt vrijgegeven, want elke plugin wordt eerst gereviewed voor een release.

I am going to fix this issue as soon as possible!

**Comment by diethard2** [comment]
Probleem opgelost en zo juist een nieuwe release gedaan van de plugin naar [https://plugins.qgis.org/plugins/b4udignl2](https://plugins.qgis.org/plugins/b4udignl2)
Nu nog wachten op approval van een reviewer zodat deze beschikbaar komt om de laatste versie te kunnen downloaden! In deze release zitten meer problemen die zijn opgelost zoals het weer goed georefereren van achtergrond raster!
