### ISSUE TITLE
'Iface' object has no attribute 'layerByName'

### ISSUE THREAD

**Issue by bvdbos** [diethard2/b4udignl#14]
Bij een recente klic-melding:

Er is een fout opgetreden bij het uitvoeren van Python code: 

AttributeError: 'Iface' object has no attribute 'layerByName' 
Traceback (most recent call last):
  File "C:/Users/bas/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\b4udignl2\B4UdigNLDialog.py", line 425, in on_openArchiveButton_clicked
    self._loadMsg()
  File "C:/Users/bas/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\b4udignl2\B4UdigNLDialog.py", line 562, in _loadMsg
    self._loadLayers()
  File "C:/Users/bas/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\b4udignl2\B4UdigNLDialog.py", line 577, in _loadLayers
    doc.loadLayers()
  File "C:/Users/bas/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\b4udignl2\core\wv.py", line 521, in loadLayers
    layer.load()
  File "C:/Users/bas/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\b4udignl2\core\wv_objects.py", line 211, in load
    layer = iface.layerByName(self.layerName)
AttributeError: 'Iface' object has no attribute 'layerByName'

Python versie: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS versie: 3.4.2-Madeira Madeira, 22034aa070 

Python pad:
C:/PROGRA~1/QGIS3~1.4/apps/qgis/./python
C:/Users/bas/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/bas/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.4/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.4\bin\python37.zip
C:\PROGRA~1\QGIS3~1.4\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib
C:\Program Files\QGIS 3.4\bin
C:\PROGRA~1\QGIS3~1.4\apps\Python37
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages\Pythonwin
C:/Users/bas/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\bas\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\b4udignl2
//10.0.0.3/data/project/30-3100/3088 Vissers/R048 Sanering fase 2 
C:\Users\bas\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\b4udignl2

**Comment by bvdbos** [comment]
Mmm, herstart van Qgis na update van de plugin lijkt afdoende te zijn geweest.
