### ISSUE TITLE
Importeren nieuwe klic melding geeft error

### ISSUE THREAD

**Issue by esmittendorff** [diethard2/b4udignl#15]
Bij het openen van een nieuwe klic melding komt de volgende error naar voren, zowel in QGIS 3.10 en 3.18. Voor zover ik kan nagaan is dag sinds deze of vorige week?  

r is een fout opgetreden bij het uitvoeren van Python code: 

AttributeError: 'NoneType' object has no attribute 'isVisible' 
Traceback (most recent call last):
  File "C:/Users/esmit/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\b4udignl2\B4UdigNLDialog.py", line 179, in _checkBoxDataStateChanged
    self._themeStateChanged(self.themeNames["data"], p_state)
  File "C:/Users/esmit/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\b4udignl2\B4UdigNLDialog.py", line 259, in _themeStateChanged
    theme.setVisibility(p_state, isVector)
  File "C:/Users/esmit/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\b4udignl2\core\wv_objects.py", line 633, in setVisibility
    show_vector, self)
  File "C:/Users/esmit/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\b4udignl2\core\wv_objects.py", line 259, in setVisibility
    theme_name)
  File "C:/Users/esmit/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\b4udignl2\core\wv_objects.py", line 264, in _setVisibilityTheme
    visible = self.isVisible(theme_name)
  File "C:/Users/esmit/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\b4udignl2\core\wv_objects.py", line 291, in isVisible
    visible = self._isVisible(theme_name)
  File "C:/Users/esmit/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\b4udignl2\core\wv_objects.py", line 302, in _isVisible
    visible = iface.visibilityForLayer(self, theme_name)
  File "C:\Users\esmit\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\b4udignl2\ifaceqgis.py", line 155, in visibilityForLayer
    visibility = self._visibility_for_layer_theme(layer, theme)
  File "C:\Users\esmit\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\b4udignl2\ifaceqgis.py", line 184, in _visibility_for_layer_theme
    visibility = self.isLayerVisible(layer)
  File "C:\Users\esmit\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\b4udignl2\ifaceqgis.py", line 162, in isLayerVisible
    value = tree_layer.isVisible()
AttributeError: 'NoneType' object has no attribute 'isVisible'

Python versie: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS versie: 3.10.3-A Coruña A Coruña, 0e1f846438 

Python pad:
C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python
C:/Users/esmit/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/esmit/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS3~1.10\apps\Python37
C:\PROGRA~1\QGIS3~1.10\apps\Python37\Scripts
C:\Program Files\QGIS 3.10\bin\python37.zip
C:\PROGRA~1\QGIS3~1.10\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib
C:\Program Files\QGIS 3.10\bin
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\Pythonwin
C:/Users/esmit/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\esmit\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\b4udignl2
C:\Users\esmit\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools\tools
C:\Users\esmit\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools

**Comment by diethard2** [comment]
Is het mogelijk om een kopie van de URL toe te sturen waarmee ik de KLIC
melding kan downloaden. Op 1 juni 2021 na mijn werk heb ik tijd om te
kijken naar de oorzaak van het probleem.

Met vriendelijke groet,
Diethard Jansen

Op vr 28 mei 2021 om 13:14 schreef esmittendorff ***@***.***>:

**Comment by esmittendorff** [comment]
Beste Diethard,

Hierbij een link naar een recente melding, ik krijg de error overigens bij alle Klic leveringen. Was vandaag in de gelegenheid om het ook op een andere machine te testen, daar werkte het wel gewoon. Mogelijk is het een issue met de installlatie op mijn machine.

https://service10.kadaster.nl/gds2/download/public/668397fa-aada-427a-b325-6bbceca8a39f


Met vriendelijke groet,

Emile Mittendorff
Projectleider Archeologie
Team Inrichting en Beheer Leefomgeving
Gemeente Deventer
Postbus 5000
7400 GC Deventer
Telefoonnummer: 06-15094816

________________________________
Van: Diethard Jansen ***@***.***>
Verzonden: maandag 31 mei 2021 07:49
Aan: diethard2/b4udignl ***@***.***>
CC: Mittendorff, Emile ***@***.***>; Author ***@***.***>
Onderwerp: Re: [diethard2/b4udignl] Importeren nieuwe klic melding geeft error (#15)


Is het mogelijk om een kopie van de URL toe te sturen waarmee ik de KLIC
melding kan downloaden. Op 1 juni 2021 na mijn werk heb ik tijd om te
kijken naar de oorzaak van het probleem.

Met vriendelijke groet,
Diethard Jansen

Op vr 28 mei 2021 om 13:14 schreef esmittendorff ***@***.***>:

**Comment by diethard2** [comment]
Bedankt voor het opsturen van deze KLIC levering!

Voordat we beginnen controleer eerst of je de laatste versie van de KLIC
viewer (versie 2.2.0) hebt geïnstalleerd. Je kunt dit controleren via de
Plug-ins manager!

Ik heb deze KLIC levering geopend in QGIS 3.14 en de melding werd op de
normale wijze geopend.
Ik heb in het verleden meegemaakt dat op een of andere manier de
lokatie instellingen van het scherm van de KLIC viewer plugin in
het QGIS3.ini bestand opeens verkeerd stonden. Dan kon je de plugin wel
opnieuw installeren, maar dat bleef fout gaan omdat er in het ini-bestand
toch nog verkeerde settings (instellingen) bleven staan!

Wanneer je werkt met QGIS worden er heel veel settings opgeslagen in dit
QGIS3.ini bestand tijdens het werken en afsluiten van QGIS die weer worden
gebruikt in volgende QGIS sessies.

Hoe kun je die QGIS3.ini vinden?
Deze staat onder windows vaak  in de volgende folder:
%APPDATA%\QGIS\QGIS3\profiles\default\QGIS

Je kunt de lokatie opvragen vanuit het Windows Command prompt met:
echo %APPDATA%\QGIS\QGIS3\profiles\default\QGIS

Of door deze gewoon in de adres-balk van de windows verkenner te plakken!
De settings voor de KLIC viewer plugin worden ook daarin opgeslagen tijdens
het gebruik van de plugin.
zie hier mijn huidige settings in de Ini file zoals ik die zie wanneer ik
dit .ini bestand open in Notepad++:

[b4udignl]
dir_last_used=C:/Users/diethard/Documents/klic/21G330980_1
last_height_dialog=438
last_width_dialog=335
last_xpos_dialog=1536
last_ypos_dialog=362

Kun je dit ook aanpassen? Jawel, maar zorg er dan wel voor dat je alle
versies van QGIS sluit en een 'echte' tekst editor gebruikt voor het openen
en bewerken van dit ini-bestand, zoals Emacs, VIM, Notepad++, Kladblok!
Gebruik in geen geval Word, Write, Wordpad of een andere tekstbewerker
(wordprocessor) deze zal er direct gehakt van maken tijdens het opslaan
waarna QGIS ontbruikbaar is!
Maak voordat je het ini bestand met een tekst editor bewerkt even een
kopie aan van het bestand.

Zoek met find naar de tekst [b4udignl]
Je krijgt nu de huidige settings te zien die worden opgeslagen voor de KLIC
viewer.
Wat je kunt doen is de regels met daarin het woord "dialog" verwijder!

Zodat ik in mijn geval alleen het volgende overhoud:

[b4udignl]
dir_last_used=C:/Users/diethard/Documents/klic/21G330980_1

Sla het bestand op en open QGIS en de KLIC viewer opnieuw.
Kijk of je nu wel de bewuste klic levering kunt openen!

Kijk je na het gebruik wederom in het  ini bestand dan zul je zien dat de
dialog settings niet meer worden aangevuld. Ik ben gestopt met het opslaan
van die settings in de meer recente versie van de KLIC viewer plugin zodat
dit soort problemen zich niet meer zouden voordoen!

Indien gewenst kan ik ook wel een aantal python statements aanleveren om
die settings te verwijderen uit het QGIS.ini bestand vanuit het QGIS Python
console. Maar bovenstaande is wellicht eenvoudiger!

Met vriendelijke groet,
Diethard Jansen



Op ma 31 mei 2021 om 17:47 schreef esmittendorff ***@***.***>:

**Comment by diethard2** [comment]
Bij nader inzien, zie ik dat nog steeds de dialog lokatie van de klic viewer plugin wordt geschreven! Dat is niet de bedoeling en zal ik er in een volgende versie van de klic viewer eruit halen!

**Comment by esmittendorff** [comment]
Bedankt, het verwijderen van de regels met "dialog" uit het ini bestand lost het probleem inderdaad op in nieuwe, lege projecten. In het bestaande project waar ik de error voor het eerst opmerkte, blijft deze error echter ook optreden na het aanpassen van het ini-bestand. Het blijkt dat in dit project (diep weggestopt in een laaggroep) al een oudere klic-melding was opgenomen (ik zie net dat je het openen van meerdere meldingen hebt uitgeschakeld, issue #7). Nadat ik deze uit het project heb verwijderd, werkt de plugin ook in dit project weer zonder problemen!

Met vriendelijke groet,
Emile Mittendorff

**Comment by ronaldhop2021** [comment]
Hallo Diethard,
Op het werken werken wij nog met Qgis 3.10. Nu wilde ik een levering van het kadaster binnen halen. Open folder en selecteer de map. De lagen worden wel ingelezen in de lagen pannel, maar de lijnen zijn niet zichtbaar op de tekening.

Heb jij een idee hoe dat kan?

gr, Ronald Hop
